### ISSUE TITLE
As a player, I should be able to check my points and rounds remaining, so I know how well I am doing

### ISSUE THREAD

**Issue by EricSihaoLin** [nyu-software-engineering/drawing-with-friends#10]
## Description:
A scoreboard and round counter should exist. Players should know who is doing well and who isn't. The game also does not go on forever, so after 2 rotations, the game should end.

## Acceptance Criteria:
 - [x] Display the current round (#55)
 - [x] Display all of the users' points in the current game (#56)
 - [x] End the game once everyone has drawn twice (#57)

## Work estimate: 
M
