### ISSUE TITLE
As a player, I should be able to guess the drawing, so that I can get points

### ISSUE THREAD

**Issue by EricSihaoLin** [nyu-software-engineering/drawing-with-friends#8]
## Description:
Once a player starts drawing, the point of the game is for the other players to guess what the current drawer is drawing into the chat box. 

The chat box is the answer box. If a user submits a correct answer, the answer is not displayed and the user should be muted to prevent cheating.

## Acceptance Criteria
- [x] Users' text is analyzed for the correct answer during a game (#49)
- [x] Users are muted once they correctly guess the answer (#50)
- [x] Users are rewarded points for guessing the correct answer (#51)
- [x] The correct answer is revealed to the players once the round is over (#52)

## Work estimate: 
L
